services:
  - type: web
    name: streamtrack-api-dev
    runtime: docker
    plan: free
    branch: dev
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
  - type: web
    name: streamtrack-api-prod
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
